CREATE DATABASE td;

CREATE USER td_user WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE td TO td_user;

CREATE USER td_admin WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE td TO td_admin;
ALTER DATABASE td OWNER TO td_admin;
